
CREATE TABLE TG_EMPLOYEE
(
   employee_id NUMBER  PRIMARY KEY,
   employee_code varchar(50) not null,
   name varchar(50) not null,
   email_id varchar(150),
   phone_number VARCHAR(15)
)^

CREATE TABLE TG_CUSTOMER
(
   CUSTOMER_ID NUMBER   PRIMARY KEY,
   CUSTOMER_CODE varchar(50) not null,
   NAME varchar(50) not null,
   email_id varchar(150),
   phone_number VARCHAR(15)
)^

CREATE TABLE TG_ROLE
(
   role_id NUMBER  PRIMARY KEY,
   name varchar(50) not null,
   description varchar(150)
)^

CREATE TABLE TG_PRIVILEGE
(
   privilege_id NUMBER  PRIMARY KEY,
   name varchar(50) not null,
   description varchar(150)
)^

CREATE TABLE TG_ROLE_PRIVILEGE
(
   role_priv_id NUMBER  PRIMARY KEY,
   role_id NUMBER not null,
   privilege_id NUMBER not null
)^

CREATE TABLE TG_USER_ROLE
(
   user_role_id NUMBER  PRIMARY KEY,
   role_id NUMBER,
   employee_id NUMBER not null
)^
CREATE TABLE TG_USER_OPT_PRIV
(
   user_opt_priv_id NUMBER  PRIMARY KEY,
   privilege_id NUMBER not null,
   employee_id NUMBER not null
)^


CREATE TABLE TG_CUSTOMER_ADDRESS (
ADDRESS_ID NUMBER   PRIMARY KEY,
ADDRESS_TYPE varchar(50) not null,
ADDRESS1 VARCHAR(150) not null,
ADDRESS2 VARCHAR(150) ,
ADDRESS3 VARCHAR(150),
CITY VARCHAR(150) not null,
STATE VARCHAR(150) not null,
COUNTRY VARCHAR(150) not null,
ZIP_CODE VARCHAR(20) not null,
CUSTOMER_ID NUMBER not null
)^

CREATE TABLE TG_EMPLOYEE_ADDRESS (
ADDRESS_ID NUMBER   PRIMARY KEY,
ADDRESS_TYPE varchar(50) not null,
ADDRESS1 VARCHAR(150) not null,
ADDRESS2 VARCHAR(150) ,
ADDRESS3 VARCHAR(150),
CITY VARCHAR(150) not null,
STATE VARCHAR(150) not null,
COUNTRY VARCHAR(150) not null,
ZIP_CODE VARCHAR(20) not null,
employee_id NUMBER not null
)^

CREATE TABLE TG_CARD_TYPE(
TYPE_ID NUMBER   PRIMARY KEY,
TYPE VARCHAR(10) NOT NULL,
TYPE_CODE VARCHAR(10) NOT NULL,
TYPE_DESCRIPTION VARCHAR(150) NOT NULL
)^

CREATE TABLE TG_CARD(
CARD_ID NUMBER   PRIMARY KEY,
CARD_NAME VARCHAR(50) NOT NULL,
CARD_CODE VARCHAR(10) NOT NULL,
TYPE_ID NUMBER NOT NULL
)^

CREATE TABLE TG_ELIGIBLE_CATEGORY(
ELIGIBLE_ID NUMBER   PRIMARY KEY,
ELIGIBLE_NAME VARCHAR(150) NOT NULL,
ELIGIBLE_AGE NUMBER ,
ELIGIBLE_SALARY BIGINT,
ELIGIBLE_SALARIED varchar(2)
)^

CREATE TABLE TG_CARD_PRICE_OFFER(
PRICE_OFFER_ID NUMBER   PRIMARY KEY,
INTEREST VARCHAR(10),
ANNUAL_CHARGE NUMBER
)^

CREATE TABLE TG_ELIGIBLE_OFFER(
ELIGIBLE_OFFER_ID  NUMBER   PRIMARY KEY,
ELIGIBLE_ID NUMBER ,
PRICE_OFFER_ID NUMBER
)^

CREATE TABLE TG_CARD_ELIGIBLE_OFFER(
ELIGIBLE_PRICE_OFFER_ID NUMBER   PRIMARY KEY,
ELIGIBLE_OFFER_ID NUMBER,
CARD_ID NUMBER
)^

CREATE TABLE TG_CUSTOMER_APP_STATUS (
CUSTOMER_APP_STATUS_ID NUMBER   PRIMARY KEY,
CUSTOMER_ID NUMBER,
CARD_ID NUMBER,
COMMENTS VARCHAR(200),
CONSTRAINT_CODE VARCHAR(20)
)^

CREATE TABLE TG_CARD_CONSTANTS (
CONSTRAINT_CODE VARCHAR(20) NOT NULL,
CONSTRAINT_VALUE VARCHAR(200) NOT NULL,
CONSTRAINT_DESC VARCHAR(200)
)^

CREATE TABLE TG_CARD_SHIPPING_DETAILS (
CARD_SHIPPING_DETAILS_ID NUMBER   PRIMARY KEY,
CUSTOMER_APP_STATUS_ID NUMBER,
SHIPPER_NAME VARCHAR(20),
TRACKING_ID VARCHAR(100),
CONSTRAINT_CODE VARCHAR(20)
)^